.gitmodules
mod-configuration-client/pom.xml
mod-configuration-server/pom.xml
pom.xml
ramls/_schemas/README.md
ramls/configuration/config.raml

Move raml-util to inside ramls directory.
Enables reliable use of pathname for $ref in schema files.

RMB-30 move raml-util

---

ramls/_schemas/kv_configuration.schema

Enable upper-case in first segment.
This came in with the recent pull/#38 for MODCONF-17, while other patterns were fixed some time ago with FOLIO-972.
Perhaps there is a copy-and-paste somewhere.

FOLIO-972 Improve UUID-like regex

---

mod-configuration-client/pom.xml
mod-configuration-server/pom.xml
pom.xml

RMB requires a recent version.
Also merge common dependencies from mod-configuration-client/pom.xml and
mod-configuration-server/pom.xml and mark junit as a test dependency.

MODCONF-20: Update vertx-unit from 3.4.1 to 3.5.3.

---

mod-configuration-server/src/test/java/org/folio/rest/RestVerticleTest.java

*Purpose*
In order to be able to easily add additional tests (e.g. for MODCONF-21)
the existing tests need splitting up and should be able to be run independently
https://issues.folio.org/browse/MODCONF-23
*Steps Involved*
* Split the existing test into separate independent chunks
* Start vert.x, embedded PostgreSQL and the module once per run of all
* Delete configuration records before each test
* Delete configuration audit records before each test
*Learning*
mod-configuration creates a set of default locale records for every tenant during activation. 
As the existing test relies on these records, these must not be deleted before each test runs and need to be compensated for in other tests. 
I've started conversations about moving these records to be optional sample records, at which …

Split existing api tests MODCONF-23

---

Jenkinsfile

Enable lint-raml with CI.
Developers can run the same script locally at `folio-tools/lint-raml/lint_raml_cop.py`
It will only report its findings, and not stop anything. With a PR, any errors will be shown, otherwise quiet.
See [folio-tools/lint-raml](https://github.com/folio-org/folio-tools/tree/master/lint-raml)

FOLIO-1027 enable lint-raml jenkinsfile

---

NEWS.md
README.md
mod-configuration-client/pom.xml
mod-configuration-server/pom.xml
mod-configuration-server/src/main/java/org/folio/rest/impl/ConfigAPI.java
mod-configuration-server/src/main/resources/data/locales.data
mod-configuration-server/src/main/resources/templates/db_scripts/schema.json
mod-configuration-server/src/test/java/org/folio/rest/RestVerticleTest.java
mod-configuration-server/src/test/java/org/folio/support/CompletableFutureExtensions.java
mod-configuration-server/src/test/java/org/folio/support/ConfigurationRecordExamples.java
mod-configuration-server/src/test/java/org/folio/support/OkapiHttpClient.java
mod-configuration-server/src/test/java/org/folio/support/Response.java
mod-configuration-server/src/test/java/org/folio/support/builders/ConfigurationRecordBuilder.java
mod-configuration-server/src/test/java/org/folio/support/builders/JsonBuilder.java
mod-configuration-server/src/test/resources/urls.csv
pom.xml

*Purpose*
https://issues.folio.org/browse/MODCONF-21
To check that only a single configuration record is present for a given combination of `module`, `configName` and `code` (optional).
*Approach*
The implementation uses four unique indexes, each with different filtering criteria (for whether code is present and whether it is a tenant or user level record).
*Learning*
It was discovered that configuration records could be either for the tenant as a whole or a user (by the presence of the `userId` property) and could be enabled or disabled (`enabled` property).
Both of these presented additional complexity in both the scenarios and implementation of these checks. Both tenant and user level records are allowed for any given combination and disabled records are omitted from the constraints. …

Unique module config name and code MODCONF-21

---

mod-configuration-server/pom.xml
pom.xml

Remove because MDGenerator is no longer part of (RMB-268)

No need for MDGenerator

---

Dockerfile
descriptors/ModuleDescriptor-template.json

Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).

MODCONF-41 FOLIO-2358 manage container memory

---

mod-configuration-server/src/main/java/org/folio/rest/impl/ConfigAPI.java
mod-configuration-server/src/test/java/org/folio/rest/RestVerticleTest.java

use proper PostgresClient.save with id passed. The postgresClient.save
without id should be deprecated!!  This makes tenant ref loading
work better. However, the damage for mod-configuration 5.2.0 persists.
mod-configation 5.2.0 entries have IDs that the tenant ref loading
can not refer to , because they were server side generated.

Fix POST item makes server side ID MODCONF-44

---

mod-configuration-client/pom.xml
mod-configuration-server/pom.xml
pom.xml

Remove unnecessary and dangerous Maven variable replacement ("variable filtering").
See https://issues.folio.org/browse/FOLIO-2548

MODCONF-51: Fix Maven ${} variable replacement in src/main/resources

---

mod-configuration-server/pom.xml
mod-configuration-server/src/main/resources/templates/db_scripts/migration/config_data.sql
mod-configuration-server/src/test/java/org/folio/rest/RestVerticleTest.java
pom.xml

Upgrade RMB from 30.0.2 to 30.2.4 fixing gin_trgm_ops schema:
https://issues.folio.org/browse/MODORDSTOR-161
Remove uuid-ossp extension that fails in pgPool environments:
https://issues.folio.org/browse/FOLIO-2447
Use md5(jsonb::text)::uuid to calculate an unique uuid.
Let RMB automatically start embedded postgres.
Remove unused PostgreSQL configuration from pom.xml.

MODCONF-54: Udate RMB to 30.2.4 fixing gin_trgm_ops schema

---

Dockerfile
Jenkinsfile
docker/docker-entrypoint.sh
mod-configuration-server/pom.xml
pom.xml

Reverts folio-org/mod-configuration#87
schema is missing for mod configuration see: 
https://issues.folio.org/browse/RMB-699
https://issues.folio.org/browse/MODINVSTOR-558

Revert "Use RMB snapshot with OpenJDK 11 MODCONF-57"

---

pom.xml

RMB 30.2.6 release notes: https://github.com/folio-org/raml-module-builder/releases/tag/v30.2.6
* [RMB-701](https://issues.folio.org/browse/RMB-701) Update to [Vert.x 3.9.2](https://github.com/vert-x3/wiki/wiki/3.9.2-Release-Notes), fixing WebClient request timeout races
* [RMB-700](https://issues.folio.org/browse/RMB-700) NPE when RestVerticle calls LogUtil.formatStatsLogMessage
* [RMB-677](https://issues.folio.org/browse/RMB-677) Close PostgreSQL connection after invalid CQL failure

MODCONF-58: Upgrade branch b5.4 (Goldenrod) to RMB 30.2.6

---

NEWS.md
mod-configuration-client/pom.xml
mod-configuration-server/pom.xml
pom.xml

* [MODCONF-63](https://issues.folio.org/browse/MODCONF-63) Upgrade RMB to 30.2.9:
* [RMB-740](https://issues.folio.org/browse/RMB-740) Use FOLIO fork of vertx-sql-client and vertx-pg-client with
the following two patches
* [RMB-739](https://issues.folio.org/browse/RMB-739) Make RMB's DB\_CONNECTIONRELEASEDELAY work again, defaults to 60 seconds
* [FOLIO-2840](https://issues.folio.org/browse/FOLIO-2840) Fix duplicate names causing 'prepared statement "XYZ" already exists'
* [RMB-738](https://issues.folio.org/browse/RMB-738) Upgrade to Vert.x 3.9.4, most notable fix: RowStream fetch
can close prematurely the stream https://github.com/eclipse-vertx/vertx-sql-client/issues/778

MODCONF-63: Upgrade branch b5.4 (Goldenrod) to RMB 30.2.9 and release

---

pom.xml

RMB 31.1.3 contains:
* [RMB-740](https://issues.folio.org/browse/RMB-740) Use FOLIO fork of vertx-sql-client and vertx-pg-client with
the following two patches
* [RMB-739](https://issues.folio.org/browse/RMB-739) Make RMB's DB\_CONNECTIONRELEASEDELAY work again, defaults to 60 seconds
* [FOLIO-2840](https://issues.folio.org/browse/FOLIO-2840) Fix duplicate names causing 'prepared statement "XYZ" already exists'
* [RMB-738](https://issues.folio.org/browse/RMB-738) Upgrade to Vert.x 3.9.4, most notable fix: RowStream fetch
can close prematurely the stream https://github.com/eclipse-vertx/vertx-sql-client/issues/778

MODCONF-64: Upgrade RMB to 31.1.3, Vert.x to 3.9.4, JUnit to 4.13.1

---

PERSONAL_DATA_DISCLOSURE.md

Please see https://issues.folio.org/browse/MODCONF-69
Note:
- Except the `userId` and `IP`, we can consider configuration is like a free text field.

MODCONF-69 Add PERSONAL_DATA_DISCLOSURE form

---

pom.xml

Most notable fix:
RMB-863 Free streamGet PreparedStatement fixing Aggressive DB Memory Consumption
https://issues.folio.org/browse/RMB-863

MODCONF-92: Update RMB to 33.1.1 and Vert.x to 4.1.4

---

mod-configuration-server/pom.xml
pom.xml

Update maven-checkstyle-plugin from 2.17 to 3.1.2
Update checkstyle from 6.11.2 to 9.2
Enable failOnViolation
Use RMB's codestyles-suppressions.xml to suppress generated-sources

maven-checkstyle-plugin 3.1.2, checkstyle 9.2

---

pom.xml

Update RMB from 33.2.2 to 33.2.4.
Update Vert.x from 4.2.1 to 4.2.3.
This updates log4j from 2.16.0 to 2.17.1. This re-enables the variable expansion in the logs, currently it literally logs
`[${FolioLoggingContext:requestid}] [${FolioLoggingContext:tenantid}] [${FolioLoggingContext:userid}] [${FolioLoggingContext:moduleid}]`

MODCONF-103: RMB 33.2.4, Vert.x 4.2.3, log4j 2.17.1 fixing [] in log

---

pom.xml

Update Vert.x from 4.2.4 to 4.2.6.
Update RMB from 33.2.5 to 33.2.8. This updates jackson-databind from 2.13.1 to 2.13.2.1 fixing https://nvd.nist.gov/vuln/detail/CVE-2020-36518

MODCONF-106: RMB 33.2.8, Vertx 4.2.6, jackson-databind 2.13.2.1

---

pom.xml

Update dependencies:
Bump RMB from 33.2.8 to 33.2.9: https://github.com/folio-org/raml-module-builder/releases/tag/v33.2.9
Bump Vert.x from 4.2.6 to 4.2.7: https://github.com/vert-x3/wiki/wiki/4.2.7-Release-Notes
This indirectly bumps jackson-databind to 2.13.2.1 and fixes https://github.com/advisories/GHSA-57j2-w4cx-62h2 = CVE-2020-36518

MODCONF-107: RMB 33.2.9, Vert.x 4.2.7

---

mod-configuration-client/pom.xml

mod-configuration-client is a software library, therefore it should not ship with a ModuleName.java.
The module that uses mod-configuration-client as a dependency needs to create an own ModuleName.java with its own name.

MODCONF-110: Don't generate ModuleName.java for mod-configuration-client

---

mod-configuration-client/pom.xml

Fix source directory for correct javadoc generation.

MODCONF-109: Fix source for javadoc

---

.github/workflows/api-doc.yml
.github/workflows/api-lint.yml
.github/workflows/api-schema-lint.yml
Jenkinsfile
README.md
ramls/configuration/config.raml

[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).

FOLIO-3678 MODCONF-137 Use GitHub Workflows api-lint and api-schema-lint and api-doc
